### ISSUE TITLE
walker stop walking when got ErrPermission

### ISSUE THREAD

**Issue by mattn** [saracen/walker#1]
When the file or directory are not permitted for the user, walker stop and return error.

**Comment by saracen** [comment]
@mattn 

Thanks for raising this issue. I've created PR https://github.com/saracen/walker/pull/2 that I intend to merge soon to address this.

If you're able to test the solution to see if it works for your use case that'd be really helpful!

**Comment by mattn** [comment]
Great! This is we want.

**Comment by saracen** [comment]
@mattn Merged!

**Comment by mattn** [comment]
Thank you.
