### ISSUE TITLE
inconsistent number of files walked for multiple runs of walker

### ISSUE THREAD

**Issue by jon-alvarado** [saracen/walker#3]
There appears to be a bug in your implementation of filewalk. I am getting differing numbers of files across each run.

➜  filewalk git:(master) ✗ go run . ~/src/media
files len 29812
➜  filewalk git:(master) ✗ go run . ~/src/media
files len 29482
➜  filewalk git:(master) ✗ go run . ~/src/media
files len 29966

Here is my test program.

```
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/saracen/walker"
)

func main() {
	flag.Parse()
	root := flag.Arg(0)

	files := walkerWalk(root)
	fmt.Println("files len", len(files))
}

func walkerWalk(root string) []string {
	paths := []string{}
	err := walker.Walk(root, func(pathname string, fi os.FileInfo) error {
		paths = append(paths, pathname)
		return nil
	})
	if err != nil {
		panic(err)
	}
	return paths
}
```

**Comment by saracen** [comment]
Hey @jon-alvarado 

`walker.Walk` calls the callback concurrently, so your slice needs to be protected with a lock. See https://github.com/saracen/walker/blob/master/walker_test.go#L76 for an example.

Let me know if that resolves your issue.

**Comment by saracen** [comment]
@jon-alvarado Did that resolve your issue?

**Comment by jon-alvarado** [comment]
Yes, that makes sense.  It works with the lock, thanks!
